### ISSUE TITLE
Anti view once isn't working properly

### ISSUE THREAD

**Issue by wasplan** [lyfe00011/levanter#108]
Tried to use it but it isn't working 
And tried to .getvv but it's showing there is nothing I have set even when I have already setvv to p
I'm the deploying the bot in Render with proper Api key and project name and ENV is setting correctly

**Comment by lyfe00011** [comment]
cross check with Env on render dashboard, also anti view once is partially broken too

**Comment by RiverNightling** [comment]
The command is .vv NOT .getvv
