### ISSUE TITLE
Koyeb deploy issue bot is not working after deployment on koyeb

### ISSUE THREAD

**Issue by Munibrustam** [lyfe00011/levanter#13]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - Platform: [e.g. Heroku]
 - Version [e.g. 3.4.5]

**Additional context**

**Comment by Munibrustam** [comment]
![download (1)](https://github.com/user-attachments/assets/3b22a5d8-aaee-4be4-8666-50ea91945f6b)
![download](https://github.com/user-attachments/assets/e9e0d005-ba39-49f8-a155-6f4e38b32207)

**Comment by lyfe00011** [comment]
change Region

**Comment by Typeshii-ha** [comment]
levanter_78a1bdff13fa94333a71d6aaa346691c4

**Comment by Typeshii-ha** [comment]
How will I add it to my WhatsApp
