### ISSUE TITLE
Fake VPS Environment

### ISSUE THREAD

**Issue by Afam007** [lyfe00011/levanter#67]
**Describe the bug**
Running the bot in a docker container , causes the bot to not restart on a cmd that changes vars  like ".status on", instead it gives a warning log

**To Reproduce**
1. Deployment in a docker container

**Expected behavior**
No warning log and bot should restart on cmd ".status on"

**Screenshots**
![Screenshot_20241101-191620_Brave](https://github.com/user-attachments/assets/d5a5e09c-826e-438f-8f8e-2b7d1528d150)

**Platform (please complete the following information):**
 - Platform: Docker container on vps
 - Version: latest

**Comment by lyfe00011** [comment]
its normal, not an issue
